### ISSUE TITLE
String Array + Abstraction

### ISSUE THREAD

**Issue by elehman16** [mlanotte1998/SoftDevApi#8]
The assignment says that they want to support "int, float, bool and String." So I think there are a few things left:
1. Figure out if they want this to support Objects as well (if yes, then this changes the rest of my comments).
2. Create a String Array class similar to that of the previous Float/Int/Bool Arrays.
3. Have all the specific array classes (bool, int, float, string) extend some generic array class that has the following methods:
    a. Length
    b. Clear

Point #3 is reasonably important since they want us to "avoid code duplication."

**Comment by mlanotte1998** [comment]
With the spec I gave , all of the kind of primitive arrays (int, bool, and float) can use the main array class and thus the array needs to take in objects. The main array can handle strings and it can also handle other objects, like for example an object that should hold a float. There is a pattern we learned in OOD I believe that will make this so that code duplication is minimal.

**Comment by elehman16** [comment]
True! I haven't thought about OOD for years so please forgive my lack of skill!
